{{- if .Values.metricsGenerator.enabled }}
{{- if gt (int .Values.metricsGenerator.replicas) 1 }}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "metrics-generator") }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "metrics-generator") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" (dict "ctx" . "component" "metrics-generator") | nindent 6 }}
  maxUnavailable: 1
{{- end }}
{{- end }}
