apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
# renovate: datasource=docker depName=docker.io/grafana/promtail
appVersion: 2.9.3
version: 6.15.5
home: https://grafana.com/loki
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
maintainers:
  - name: Loki Maintainers
    email: lokiproject@googlegroups.com
  - name: unguiculus
