{{- if .Values.memcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}-memcached
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.memcachedLabels" . | nindent 4 }}
spec:
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    targetPort: 9150
  selector:
    {{- include "tempo.memcachedSelectorLabels" . | nindent 4 }}
{{- end}}