apiVersion: "v2"
name: "enterprise-logs-simple"
type: application
version: "1.3.0"
appVersion: "v1.4.0"
kubeVersion: "^1.10.0-0"
description: "DEPRECATED Grafana Enterprise Logs (Simple Scalable)"
deprecated: true
home: "https://grafana.com/products/enterprise/logs/"
dependencies:
  - name: loki-simple-scalable
    version: ^0.3.0
    repository: https://grafana.github.io/helm-charts
  - name: minio
    alias: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: minio.enabled
