apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tempo.compactorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.compactorLabels" . | nindent 4 }}
  {{- with .Values.compactor.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.compactor.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "tempo.compactorSelectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "tempo.compactorLabels" . | nindent 8 }}
        {{- include "tempo.gossipRing.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-tempo.yaml") . | sha256sum }}
        {{- with .Values.compactor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "tempo.serviceAccountName" . }}
      containers:
        - args:
            - -target=compactor
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
            {{- with .Values.compactor.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "tempo.compactorImage" . }}
          imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
          name: compactor
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 7946
              name: http-memberlist
          {{- with .Values.compactor.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.compactor.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.compactor.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
            {{- with .Values.compactor.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.compactor.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.compactor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.compactor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            name: {{ template "tempo.fullname" . }}
          name: tempo-conf
        {{- with .Values.compactor.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
