---
loki:
  commonConfig:
    replication_factor: 1
read:
  replicas: 1
  initContainers:
    - name: my-init-container
      image: busybox:latest
      command: ['sh', '-c', 'echo hello']
write:
  replicas: 1
  initContainers:
    - name: my-init-container
      image: busybox:latest
      command: ['sh', '-c', 'echo hello']
