global:
  # -- Common labels for all object directly managed by this chart.
  # scope: *
  commonLabels: {}

# -- Overrides the chart's name
nameOverride: ""
# -- Overrides the chart's computed fullname
fullnameOverride: ""
# -- Image pull secrets for Docker images
imagePullSecrets: []
# -- hostAliases to add
hostAliases: []
#  - ip: 1.2.3.4
#    hostnames:
#      - domain.tld

image:
  # -- Docker image repository
  repository: docker.io/grafana/tempo-vulture
  # -- Overrides the image tag whose default is the chart's appVersion
  tag: ""
  # -- Docker image pull policy
  pullPolicy: IfNotPresent

# -- Number of replicas of Tempo Vulture
replicas: 1
# -- Common labels for all pods
podLabels: {}
# -- Common annotations for all pods
podAnnotations: {}
# -- Common annotations for the deployment and service
annotations: {}
# -- The number of old ReplicaSets to retain to allow rollback
revisionHistoryLimit: 10
# -- Additional CLI args for the vulture
extraArgs: []
# -- Environment variables to add to the vulture pods
extraEnv: []
# -- Environment variables from secrets or configmaps to add to the vulture pods
extraEnvFrom: []
# -- Resource requests and limits for the vulture
resources: {}
# -- Node selector for vulture pods
nodeSelector: {}
# -- Tolerations for vulture pods
tolerations: []
# -- SecurityContext holds container-level security attributes and common container settings
securityContext: {}
# -- podSecurityContext holds pod-level security attributes and common container settings
podSecurityContext: {}

serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  create: true
  # -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: null
  # -- Image pull secrets for the service account
  imagePullSecrets: []
  # -- Annotations for the service account
  annotations: {}

# PodMonitor configuration
podMonitor:
  # -- If enabled, PodMonitor resources for Prometheus Operator are created
  enabled: false
  # -- Alternative namespace for PodMonitor resources
  namespace: null
  # -- Namespace selector for PodMonitor resources
  namespaceSelector: {}
  # -- PodMonitor annotations
  annotations: {}
  # -- Additional PodMonitor labels
  labels: {}
  # -- PodMonitor scrape interval
  interval: null
  # -- PodMonitor scrape timeout in Go duration format (e.g. 15s)
  scrapeTimeout: null

tempoAddress:
  # -- the url towards your Tempo distributor, e.g. http://distributor
  push:
  # -- the url towards your Tempo query-frontend, e.g. http://query-frontend:3100
  query:
