apiVersion: v2
name: tempo
description: Grafana Tempo Single Binary Mode
type: application
version: 1.10.1
appVersion: 2.5.0
engine: gotpl
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
sources:
  - https://github.com/grafana/tempo
maintainers:
  - name: joe-elliott
    email: number101010@gmail.com
  - name: swartz-k
    email: 9215868@gmail.com
  - name: annanay25
  - name: mdisibio
  - name: dgzlopes
  - name: mapno
  - name: Sheikh-Abubaker
    email: sheikhabubaker761@gmail.com
