apiVersion: v2
name: loki-distributed
description: Helm chart for Grafana Loki in microservices mode
type: application
appVersion: 2.6.1
version: 0.56.7
home: https://grafana.github.io/helm-charts
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
  - name: unguiculus
