apiVersion: v2
name: grafana-agent-operator
description: A Helm chart for Grafana Agent Operator
type: application
version: 0.2.16
appVersion: "0.34.1"
home: https://grafana.com/docs/agent/v0.32/
icon: https://raw.githubusercontent.com/grafana/agent/v0.32.1/docs/sources/assets/logo_and_name.png
sources:
  - https://github.com/grafana/agent/tree/v0.32.1/pkg/operator
maintainers:
  - name: Grafana Agent Team
    email: grafana-agent-team@googlegroups.com
