apiVersion: v2
name: grafana-agent-operator
description: A Helm chart for Grafana Agent Operator
type: application
version: 0.2.1
appVersion: "0.24.2"
home: https://grafana.com/docs/agent/latest/
icon: https://raw.githubusercontent.com/grafana/agent/v0.24.2/docs/assets/logo_and_name.png
sources:
  - https://github.com/grafana/agent/tree/v0.24.2/pkg/operator
maintainers:
  - name: Grafana Agent Team
    email: grafana-agent-team@googlegroups.com
