apiVersion: v2
name: grafana-agent-operator
description: A Helm chart for Grafana Agent Operator
type: application
version: 0.2.12
appVersion: "0.31.3"
home: https://grafana.com/docs/agent/v0.30/
icon: https://raw.githubusercontent.com/grafana/agent/v0.31.2/docs/sources/assets/logo_and_name.png
sources:
  - https://github.com/grafana/agent/tree/v0.31.2/pkg/operator
maintainers:
  - name: Grafana Agent Team
    email: grafana-agent-team@googlegroups.com
