{{ if .Values.tokengen.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "enterprise-metrics.tokengenFullname" . }}
  labels:
    {{- include "enterprise-metrics.tokengenLabels" . | nindent 4 }}
    {{- with .Values.tokengen.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.tokengen.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    "helm.sh/hook": post-install
{{- end }}
