{{- if .Values.admin_api.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mimir.adminApiFullname" . }}
  labels:
    {{- include "mimir.adminApiLabels" . | nindent 4 }}
    {{- if .Values.useGEMLabels }}{{- include "mimir.gemExtraLabels" . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.adminApiSelectorLabels" . | nindent 6 }}
{{ toYaml .Values.admin_api.podDisruptionBudget | indent 2 }}
{{- end -}}
