apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "enterprise-logs.compactorFullname" . }}
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
    {{- with .Values.compactor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/part-of: memberlist
  annotations:
    {{- with .Values.compactor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.compactor.replicas }}
  selector:
    matchLabels:
      {{- include "enterprise-logs.compactorSelectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.compactor.strategy | nindent 4 }}
  serviceName: {{ template "enterprise-logs.compactorFullname" . }}
  {{- if .Values.compactor.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        {{- if .Values.compactor.persistentVolume.annotations }}
        annotations:
          {{ toYaml .Values.compactor.persistentVolume.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.compactor.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.compactor.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.compactor.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{ toYaml .Values.compactor.persistentVolume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.compactor.persistentVolume.size }}"
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "enterprise-logs.compactorSelectorLabels" . | nindent 8 }}
        {{- with .Values.compactor.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/part-of: memberlist
      annotations:
        {{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.compactor.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "loki.serviceAccountName" . }}
      {{- if .Values.compactor.priorityClassName }}
      priorityClassName: {{ .Values.compactor.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.compactor.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.compactor.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.compactor.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.compactor.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.compactor.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.compactor.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.compactor.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
          {{- if .Values.useExternalConfig }}
            secretName: {{ .Values.externalConfigName }}
          {{- else }}
            secretName: enterprise-logs-config
          {{- end }}
        - name: license
          secret:
          {{- if .Values.useExternalLicense }}
            secretName: {{ .Values.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        - name: storage
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- if .Values.compactor.extraVolumes }}
        {{ toYaml .Values.compactor.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        {{- if .Values.compactor.extraContainers }}
        {{ toYaml .Values.compactor.extraContainers | nindent 8 }}
        {{- end }}
        - name: compactor
          image: "{{ template "enterprise-logs.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -target=compactor
            - -config.file=/etc/loki/config/config.yaml
            {{- if .Values.minio.enabled }}
            - -admin.client.backend-type=s3
            - -admin.client.s3.endpoint={{ template "enterprise-logs.minio" . }}
            - -admin.client.s3.bucket-name=enterprise-logs-admin
            - -admin.client.s3.access-key-id={{ .Values.minio.accessKey }}
            - -admin.client.s3.secret-access-key={{ .Values.minio.secretKey }}
            - -admin.client.s3.insecure=true
            {{- end }}
            {{- range $key, $value := .Values.compactor.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/enterprise-logs/license
            - name: storage
              mountPath: /var/loki
            - name: tmp
              mountPath: /tmp
            {{- if .Values.compactor.extraVolumeMounts }}
            {{ toYaml .Values.compactor.extraVolumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.compactor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.compactor.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.compactor.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.compactor.containerSecurityContext | nindent 12 }}
          env:
            {{- if .Values.compactor.env }}
            {{- toYaml .Values.compactor.env | nindent 12 }}
            {{- end }}
