apiVersion: v1
data:
  license.jwt: Tk9UQVZBTElETElDRU5TRQ==
kind: Secret
metadata:
  labels:
    app: enterprise-metrics-license
    app.kubernetes.io/managed-by: Helmraiser
    chart: enterprise-metrics-1.4.0
    heritage: Helm
    release: enterprise-metrics
  name: enterprise-metrics-license
  namespace: enterprise-metrics
