apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise-metrics-gateway
    app.kubernetes.io/managed-by: Helmraiser
    chart: enterprise-metrics-1.4.0
    heritage: Helm
    release: enterprise-metrics
  name: enterprise-metrics-gateway
  namespace: enterprise-metrics
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: enterprise-metrics-gateway
    release: enterprise-metrics
  type: ClusterIP
