apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: enterprise-metrics
    app.kubernetes.io/managed-by: Helmraiser
    chart: enterprise-metrics-1.4.0
    heritage: Helm
    release: enterprise-metrics
  name: enterprise-metrics
  namespace: enterprise-metrics
