{{- if and .Values.querier.enabled (gt (int .Values.querier.replicas) 1) }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.querierFullname" . }}
  labels:
    {{- include "loki.querierLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.querierSelectorLabels" . | nindent 6 }}
  {{- with .Values.querier.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
