{{- if gt (int .Values.querier.replicas) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.querierLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.querierSelectorLabels" . | nindent 6 }}
  maxUnavailable: 1
{{- end }}
