apiVersion: v2
name: loki-simple-scalable
description: Helm chart for Grafana Loki in simple, scalable mode
type: application
appVersion: 2.5.0
version: 1.4.4
home: https://grafana.github.io/helm-charts
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
dependencies:
  - name: minio
    alias: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: minio.enabled
maintainers:
  - name: trevorwhitney
