apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise-logs.gatewayFullname" . }}
  labels:
    {{- include "enterprise-logs.gatewayLabels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      {{- include "enterprise-logs.gatewaySelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.gateway.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "enterprise-logs.gatewaySelectorLabels" . | nindent 8 }}
        {{- with .Values.gateway.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- end}}
        {{- with .Values.gateway.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "loki.serviceAccountName" . }}
      {{- if .Values.gateway.priorityClassName }}
      priorityClassName: {{ .Values.gateway.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.gateway.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.gateway.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.gateway.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gateway
          image: "{{ template "enterprise-logs.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -target=gateway
            - -config.file=/etc/loki/config/config.yaml
            {{- if .Values.minio.enabled }}
            - -admin.client.backend-type=s3
            - -admin.client.s3.endpoint={{ template "enterprise-logs.minio" . }}
            - -admin.client.s3.bucket-name=enterprise-logs-admin
            - -admin.client.s3.access-key-id={{ .Values.minio.accessKey }}
            - -admin.client.s3.secret-access-key={{ .Values.minio.secretKey }}
            - -admin.client.s3.insecure=true
            {{- end }}
            {{- if .Values.gateway.useDefaultProxyURLs }}
            - -gateway.proxy.default.url=http://{{ template "enterprise-logs.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.admin-api.url=http://{{ template "enterprise-logs.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.distributor.url=http://{{ template "enterprise-logs.fullname" . }}-distributor.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.ingester.url=http://{{ template "enterprise-logs.fullname" . }}-ingester.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.query-frontend.url=http://{{ template "enterprise-logs.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.ruler.url=http://{{ template "enterprise-logs.fullname" . }}-ruler.{{ .Release.Namespace }}.svc:3100
            {{- end }}
            {{- range $key, $value := .Values.gateway.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/enterprise-logs/license
            - name: storage
              mountPath: /data
              subPath: {{ .Values.gateway.persistence.subPath }}
            {{- if .Values.gateway.extraVolumeMounts }}
            {{ toYaml .Values.gateway.extraVolumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.gateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.gateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.gateway.containerSecurityContext | nindent 12 }}
          env:
            {{- if .Values.gateway.env }}
            {{ toYaml .Values.gateway.env | nindent 12 }}
            {{- end }}
        {{- with .Values.gateway.extraContainers }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.gateway.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.gateway.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.gateway.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.gateway.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
          {{- if .Values.useExternalConfig }}
            secretName: {{ .Values.externalConfigName }}
          {{- else }}
            secretName: enterprise-logs-config
          {{- end }}
        - name: license
          secret:
          {{- if .Values.useExternalLicense }}
            secretName: {{ .Values.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        - name: storage
          emptyDir: {}
        {{- if .Values.gateway.extraVolumes }}
        {{ toYaml .Values.gateway.extraVolumes | nindent 8 }}
        {{- end }}
