{{- with .Values.gateway }}
{{- if and .enabled .basicAuth.enabled (not .basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.gatewayFullname" $ }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
  .htpasswd: |
    {{- tpl .basicAuth.htpasswd $ | nindent 4 }}
{{- end }}
{{- end }}
