---
apiVersion: v2
name: lgtm-distributed
description: Umbrella chart for a distributed Loki, Grafana, Tempo and Mimir stack
type: application
version: 2.1.0
appVersion: "^7.3.9"

home: https://grafana.com/oss/
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116

sources:
  - https://grafana.github.io/helm-charts
  - https://github.com/grafana/grafana
  - https://github.com/grafana/loki
  - https://github.com/grafana/mimir
  - https://github.com/grafana/tempo

keywords:
  - monitoring
  - traces
  - metrics
  - logs

annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Grafana
      url: https://github.com/grafana/grafana
    - name: Loki
      url: https://github.com/grafana/loki
    - name: Mimir
      url: https://github.com/grafana/mimir
    - name: Tempo
      url: https://github.com/grafana/tempo

maintainers:
  - name: timberhill

dependencies:
  - name: grafana
    alias: grafana
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: "^7.3.9"
  - name: loki-distributed
    alias: loki
    condition: loki.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^0.79.0"
  - name: mimir-distributed
    alias: mimir
    condition: mimir.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^5.3.0"
  - name: tempo-distributed
    alias: tempo
    condition: tempo.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^1.9.2"
  - name: oncall
    alias: grafana-oncall
    condition: grafana-oncall.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^1.3.114"
