{{- if .Values.graphite.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise-metrics.fullname" . }}-graphite-querier
  labels:
    app: {{ template "enterprise-metrics.name" . }}-graphite-querier
    chart: {{ template "enterprise-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.graphite_querier.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.graphite_querier.replicas }}
  selector:
    matchLabels:
      app: {{ template "enterprise-metrics.name" . }}-graphite-querier
      release: {{ .Release.Name }}
  strategy:
    {{- toYaml .Values.graphite_querier.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "enterprise-metrics.name" . }}-graphite-querier
        release: {{ .Release.Name }}
        {{- with .Values.graphite_querier.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
{{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
{{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- end}}
        {{- with .Values.graphite_querier.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "enterprise-metrics.serviceAccountName" . }}
    {{- if .Values.graphite_querier.priorityClassName }}
      priorityClassName: {{ .Values.graphite_querier.priorityClassName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.graphite_querier.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.graphite_querier.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -target=graphite-querier
            - -config.file=/etc/enterprise-metrics/enterprise-metrics.yaml
            - -graphite.enabled=true
            - -graphite.querier.query-address=http://{{ template "enterprise-metrics.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc:{{ .Values.config.server.http_listen_port }}/api/prom
            - -graphite.querier.graphite-fallback=http://{{ template "enterprise-metrics.fullname" . }}-graphite-web.{{ .Release.Namespace}}.svc:{{ .Values.config.server.http_listen_port }}
            - -graphite.querier.schemas.default-storage-schemas-file=/etc/graphite-proxy/storage-schemas.conf
            - -graphite.querier.schemas.default-storage-aggregations-file=/etc/graphite-proxy/storage-aggregations.conf
            {{- if .Values.minio.enabled }}
            - -admin.client.backend-type=s3
            - -admin.client.s3.endpoint={{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc:9000
            - -admin.client.s3.bucket-name=enterprise-metrics-admin
            - -admin.client.s3.access-key-id=enterprise-metrics
            - -admin.client.s3.secret-access-key=supersecret
            - -admin.client.s3.insecure=true
            {{- end }}
          {{- range $key, $value := .Values.graphite_querier.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.graphite_querier.extraVolumeMounts }}
              {{ toYaml .Values.graphite_querier.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/enterprise-metrics
            - name: runtime-config
              mountPath: /var/enterprise-metrics
            - name: graphite-schemas
              mountPath: /etc/graphite-proxy
            - name: license
              mountPath: /license
            - name: storage
              mountPath: "/data"
              subPath: {{ .Values.graphite_querier.persistence.subPath }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.config.server.grpc_listen_port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.graphite_querier.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.graphite_querier.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.graphite_querier.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- if .Values.graphite_querier.env }}
              {{- toYaml .Values.graphite_querier.env | nindent 12 }}
            {{- end }}
{{- if .Values.graphite_querier.extraContainers }}
{{ toYaml .Values.graphite_querier.extraContainers | indent 8}}
{{- end }}
      nodeSelector:
        {{- toYaml .Values.graphite_querier.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.graphite_querier.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.graphite_querier.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.graphite_querier.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
{{- if .Values.useExternalConfig }}
            secretName: {{ .Values.externalConfigSecretName }}
{{- else }}
            secretName: {{ template "enterprise-metrics.fullname" . }}
{{- end }}
        - name: runtime-config
          configMap:
            name: {{ template "enterprise-metrics.fullname" . }}-runtime
        - name: graphite-schemas
          configMap:
            name: {{ template "enterprise-metrics.fullname" . }}-graphite-schemas
{{- if .Values.graphite_querier.extraVolumes }}
{{ toYaml .Values.graphite_querier.extraVolumes | indent 8}}
{{- end }}
        - name: license
          secret:
            secretName: {{ .Values.license.secretName }}
        - name: storage
          emptyDir: {}
{{- end -}}
