{{- if .Values.graphite.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-metrics.fullname" . }}-graphite-web
  labels:
    app: {{ template "enterprise-metrics.fullname" . }}-graphite-web
    chart: {{ template "enterprise-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.graphite_web.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.graphite_web.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: graphite-http
      targetPort: 80
  selector:
    app: {{ template "enterprise-metrics.fullname" . }}-graphite-web
    release: {{ .Release.Name }}
{{- end -}}
