{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}
    chart: {{ template "metrics_enterprise.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.rbac.pspEnabled }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "metrics_enterprise.fullname" . }}]
{{- end }}
{{- end }}
