{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "metrics_enterprise.name" . }}
    chart: {{ template "metrics_enterprise.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  name: {{ template "metrics_enterprise.serviceAccountName" . }}
{{- end }}
