{{- if gt (int .Values.distributor.replicas) 1 }}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "distributor") }}
  labels:
    {{- include "tempo.distributorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" (dict "ctx" . "component" "distributor") | nindent 6 }}
  maxUnavailable: 1
{{- end }}
