{{- if .Values.compactor.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.compactorFullname" . }}
  labels:
    {{- include "mimir.compactorLabels" . | nindent 4 }}
    {{- if .Values.useGEMLabels }}{{- include "mimir.gemExtraLabels" . | nindent 4 }}{{- end }}
  annotations:
    {{- toYaml .Values.compactor.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.compactor.replicas }}
  selector:
    matchLabels:
      {{- include "mimir.compactorSelectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.compactor.strategy | nindent 4 }}
  serviceName: {{ template "mimir.fullname" . }}-compactor
  {{- if .Values.compactor.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        {{- if .Values.compactor.persistentVolume.annotations }}
        annotations:
          {{ toYaml .Values.compactor.persistentVolume.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.compactor.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.compactor.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.compactor.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{ toYaml .Values.compactor.persistentVolume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.compactor.persistentVolume.size }}"
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "mimir.compactorLabels" . | nindent 8 }}
        {{- if .Values.useGEMLabels }}{{- include "mimir.gemCompactorPodLabels" . | nindent 8 }}{{- end }}
        {{- with .Values.compactor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.compactor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "mimir.serviceAccountName" . }}
      {{- if .Values.compactor.priorityClassName }}
      priorityClassName: {{ .Values.compactor.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.compactor.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.compactor.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.compactor.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.compactor.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.compactor.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.compactor.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.externalConfigSecretName }}
        - name: runtime-config
          configMap:
            name: {{ template "mimir.fullname" . }}-runtime
        {{- if not .Values.compactor.persistentVolume.enabled }}
        - name: storage
          emptyDir: {}
        {{- end }}
        {{- if .Values.compactor.extraVolumes }}
        {{ toYaml .Values.compactor.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        {{- if .Values.compactor.extraContainers }}
        {{ toYaml .Values.compactor.extraContainers | nindent 8 }}
        {{- end }}
        - name: compactor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=compactor"
            - -activity-tracker.filepath=
            - "-config.file=/etc/mimir/mimir.yaml"
            {{- range $key, $value := .Values.compactor.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            {{- if .Values.compactor.extraVolumeMounts }}
            {{ toYaml .Values.compactor.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/mimir
            - name: runtime-config
              mountPath: /var/mimir
            - name: storage
              mountPath: "/data"
              {{- if .Values.compactor.persistentVolume.subPath }}
              subPath: {{ .Values.compactor.persistentVolume.subPath }}
              {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ include "mimir.serverHttpListenPort" . }}
              protocol: TCP
            - name: grpc
              containerPort: {{ include "mimir.serverGrpcListenPort" . }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.compactor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.compactor.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.compactor.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- if .Values.compactor.env }}
              {{- toYaml .Values.compactor.env | nindent 12 }}
            {{- end }}
{{- end -}}
