{{- if ne .Values.config.storage.engine "blocks" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}-table-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}-table-manager
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.table_manager.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.table_manager.replicas }}
  selector:
    matchLabels:
      app: {{ template "metrics_enterprise.name" . }}-table-manager
      release: {{ .Release.Name }}
  strategy:
    {{- toYaml .Values.table_manager.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "metrics_enterprise.name" . }}-table-manager
        name: {{ template "metrics_enterprise.name" . }}-table-manager
        target: table-manager
        release: {{ .Release.Name }}
        {{- with .Values.table_manager.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
{{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
{{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- end}}
        {{- with .Values.table_manager.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "metrics_enterprise.serviceAccountName" . }}
    {{- if .Values.table_manager.priorityClassName }}
      priorityClassName: {{ .Values.table_manager.priorityClassName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.table_manager.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.table_manager.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=table-manager"
            - "-config.file=/etc/metrics-enterprise/metrics-enterprise.yaml"
          {{- range $key, $value := .Values.table_manager.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.table_manager.extraVolumeMounts }}
              {{ toYaml .Values.table_manager.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/metrics-enterprise
            - name: license
              mountPath: /license
            - name: storage
              mountPath: "/data"
              subPath: {{ .Values.table_manager.persistence.subPath }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.table_manager.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.table_manager.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.table_manager.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- if .Values.table_manager.env }}
              {{- toYaml .Values.table_manager.env | nindent 12 }}
            {{- end }}
{{- if .Values.table_manager.extraContainers }}
{{ toYaml .Values.table_manager.extraContainers | indent 8}}
{{- end }}
      nodeSelector:
        {{- toYaml .Values.table_manager.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.table_manager.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.table_manager.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.table_manager.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
{{- if .Values.useExternalConfig }}
            secretName: {{ .Values.externalConfigSecretName }}
{{- else }}
            secretName: {{ template "metrics_enterprise.fullname" . }}
{{- end }}
{{- if .Values.table_manager.extraVolumes }}
{{ toYaml .Values.table_manager.extraVolumes | indent 8}}
{{- end }}
        - name: license
          secret:
            secretName: {{ template "metrics_enterprise.fullname" . }}-license
        - name: storage
          emptyDir: {}
{{- end -}}
