apiVersion: v2
name: grafana-mcp
version: 0.3.1
appVersion: 0.8.2
kubeVersion: "^1.8.0-0"
deprecated: true
description: MCP server for Grafana.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
sources:
  - https://github.com/grafana/mcp-grafana
  - https://github.com/grafana-community/helm-charts
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/grafana-community/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/mcp-grafana
maintainers:
  - name: Mohammad Abubaker
    email: sheikhabubaker761@gmail.com
    url: https://github.com/Sheikh-Abubaker
  - name: Jan-Otto Kr√∂pke
    email: github@jkroepke.de
    url: https://github.com/jkroepke
  - name: Aviv Guiser
    email: avivguiser@gmail.com
    url: https://github.com/KyriosGN0
  - name: Quentin Bisson
    email: quentin.bisson@gmail.com
    url: https://github.com/QuentinBisson
type: application
keywords:
  - monitoring
  - mcp
