apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.querierFullname" . }}
  labels:
    {{- include "loki.querierLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: gossip-ring
spec:
  replicas: {{ .Values.querier.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "loki.querierSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") $ | sha256sum }}
        {{- with .Values.loki.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.querier.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "loki.querierLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: gossip-ring
    spec:
      serviceAccountName: {{ include "loki.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: {{ .Values.querier.terminationGracePeriodSeconds }}
      containers:
        - name: querier
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/loki.yaml
            - -target=querier
            - -print-config-stderr
            {{- with .Values.querier.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-gossip
              containerPort: 7946
              protocol: TCP
          {{- with .Values.querier.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.querier.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: boltdb-cache
              mountPath: /var/loki
          resources:
            {{- toYaml .Values.querier.resources | nindent 12 }}
      {{- with .Values.querier.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "loki.fullname" . }}
        - name: boltdb-cache
          emptyDir: {}
