{{- if .Values.tempoQuery.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tempo.name" . }}-query
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
data:
  tempo-query.yaml: |
    backend: {{ template "tempo.fullname" . }}:{{ .Values.tempo.server.http_listen_port }}
{{- end }}