apiVersion: v2
version: 1.4.1
appVersion: v1.4.1
description: 'Grafana Enterprise Metrics'
engine: gotpl
home: https://grafana.com/products/enterprise/metrics
icon: https://grafana.com/static/img/menu/metrics-enterprise.svg
kubeVersion: ^1.10.0-0
name: enterprise-metrics
dependencies:
  - name: memcached
    alias: memcached
    version: 5.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: memcached
    alias: memcached-queries
    version: 5.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-queries.enabled
  - name: memcached
    alias: memcached-metadata
    version: 5.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-metadata.enabled
  - name: minio
    alias: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: minio.enabled
  - name: consul
    alias: consul
    version: 0.25.0
    repository: https://helm.releases.hashicorp.com
    condition: consul.enabled
