apiVersion: v2
name: grafana
version: 10.5.15
appVersion: 12.3.1
kubeVersion: "^1.8.0-0"
deprecated: true
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana-community/helm-charts
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/grafana-community/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/grafana
maintainers:
  - name: Jan-Otto Kr√∂pke
    email: github@jkroepke.de
    url: https://github.com/jkroepke
  - name: Quentin Bisson
    email: quentin.bisson@gmail.com
    url: https://github.com/QuentinBisson
type: application
keywords:
  - monitoring
  - metric
