apiVersion: v2
name: grafana
version: 6.7.2
appVersion: 7.5.2
kubeVersion: '^1.8.0-0'
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: zanhsieh
    email: zanhsieh@gmail.com
  - name: rtluckie
    email: rluckie@cisco.com
  - name: maorfr
    email: maor.friedman@redhat.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: torstenwalter
    email: mail@torstenwalter.de
engine: gotpl
type: application
