apiVersion: v2
name: grafana
version: 7.3.6
# renovate: datasource=docker depName=docker.io/grafana/grafana
appVersion: 10.3.3
kubeVersion: "^1.8.0-0"
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana/helm-charts
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/grafana
maintainers:
  - name: zanhsieh
    email: zanhsieh@gmail.com
  - name: rtluckie
    email: rluckie@cisco.com
  - name: maorfr
    email: maor.friedman@redhat.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: torstenwalter
    email: mail@torstenwalter.de
type: application
keywords:
  - monitoring
  - metric
