apiVersion: v2
name: loki-canary
description: Helm chart for Grafana Loki Canary
type: application
appVersion: 2.2.0
version: 0.3.3
home: https://github.com/grafana/helm-charts
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
  - name: unguiculus
