apiVersion: "v1"
name: fluent-bit
version: 2.6.0
appVersion: v2.1.0
kubeVersion: "^1.10.0-0"
description: "Uses fluent-bit Loki go plugin for gathering logs and sending them to Loki"
# This Helm chart is deprecated and no longer maintained.
deprecated: true
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
sources:
- https://github.com/grafana/loki
maintainers:
- name: Loki Maintainers
  email: lokiproject@googlegroups.com
engine: gotpl
