{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ga-operator.operator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: operator
{{ include "ga-operator.labels" . | indent 4 }}
{{- end -}}