apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enterprise-metrics
    app.kubernetes.io/managed-by: Helmraiser
    chart: enterprise-metrics-1.4.0
    heritage: Helm
    release: enterprise-metrics
  name: enterprise-metrics
  namespace: enterprise-metrics
rules:
- apiGroups:
  - extensions
  resourceNames:
  - enterprise-metrics
  resources:
  - podsecuritypolicies
  verbs:
  - use
