{{- $clusterPort := regexReplaceAll ".+[:]" (default "0.0.0.0:9094" (include "mimir.alertmanagerClusterBindAddress" .) ) "" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mimir.fullname" . }}-alertmanager-headless
  labels:
    {{- include "mimir.alertmanagerLabels" . | nindent 4 }}
    {{- if .Values.useGEMLabels }}{{- include "mimir.gemExtraLabels" . | nindent 4 }}{{- end }}
    {{- with .Values.alertmanager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ include "mimir.serverHttpListenPort" . }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ include "mimir.serverGrpcListenPort" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
    - port: {{ $clusterPort }}
      protocol: TCP
      name: cluster
  selector:
    {{- include "mimir.alertmanagerSelectorLabels" . | nindent 4 }}
