apiVersion: v2
name: rollout-operator
description: "Grafana rollout-operator"
type: application
version: 0.9.1
appVersion: v0.8.1
home: https://github.com/grafana/rollout-operator
kubeVersion: ^1.10.0-0
