apiVersion: v2
name: rollout-operator
description: "Grafana rollout-operator"
type: application
version: 0.13.0
appVersion: v0.11.0
home: https://github.com/grafana/rollout-operator
kubeVersion: ^1.10.0-0
