apiVersion: "v2"
name: "enterprise-logs"
type: application
version: "2.5.1"
deprecated: true
appVersion: "v1.5.2"
kubeVersion: "^1.10.0-0"
description: "Grafana Enterprise Logs"
home: "https://grafana.com/products/enterprise/logs/"
dependencies:
- name: "loki-distributed"
  version: "0.80.6"
  repository: "https://grafana.github.io/helm-charts"
- name: minio
  alias: minio
  version: 4.0.12
  repository: https://charts.min.io/
  condition: minio.enabled
