{{- if and .Values.memcachedIndexQueries.enabled (gt (int .Values.memcachedIndexQueries.replicas) 1) }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.memcachedIndexQueriesFullname" . }}
  labels:
    {{- include "loki.memcachedIndexQueriesLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.memcachedIndexQueriesSelectorLabels" . | nindent 6 }}
  {{- with .Values.memcachedIndexQueries.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
