name: Check CODEOWNERS

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - name: install yq
        run: |
          sudo snap install yq
      - name: generate CODEOWNERS
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS
      - name: check CODEOWNERS for modifications
        run: |
          git diff --exit-code || echo "::warning::There is at least one codeowner mismatch."
