apiVersion: v2
name: tempo-distributed
description: Grafana Tempo in MicroService mode
type: application
version: 1.62.1
appVersion: 2.9.0
engine: gotpl
home: https://grafana.com/docs/tempo/latest/
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
sources:
  - https://github.com/grafana/tempo
maintainers:
  - name: Ilia Lazebnik
    email: Ilia.lazebnik@gmail.com
    url: https://github.com/DrFaust92
  - name: Mohammad Abubaker
    email: sheikhabubaker761@gmail.com
    url: https://github.com/Sheikh-Abubaker
  - name: Quentin Bisson
    email: quentin.bisson@gmail.com
    url: https://github.com/QuentinBisson
dependencies:
  - name: minio
    alias: minio
    version: 4.1.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: grafana-agent-operator
    alias: grafana-agent-operator
    version: 0.5.2
    repository: https://grafana.github.io/helm-charts
    condition: metaMonitoring.grafanaAgent.installOperator
  - name: rollout-operator
    alias: rollout_operator
    repository: https://grafana.github.io/helm-charts
    version: 0.40.0
    condition: rollout_operator.enabled
