apiVersion: v2
name: tempo-distributed
description: Grafana Tempo in MicroService mode
type: application
version: 1.8.6
# renovate: datasource=docker depName=docker.io/grafana/tempo
appVersion: 2.3.1
engine: gotpl
home: https://grafana.com/docs/tempo/latest/
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
sources:
  - https://github.com/grafana/tempo
maintainers:
  - name: joe-elliott
    email: number101010@gmail.com
  - name: swartz-k
    email: 9215868@gmail.com
  - name: annanay25
  - name: mdisibio
  - name: mapno
  - name: BitProcessor
  - name: faustodavid
  - name: zalegrala
dependencies:
  - name: minio
    alias: minio
    version: 4.0.12
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: grafana-agent-operator
    alias: grafana-agent-operator
    version: 0.2.2
    repository: https://grafana.github.io/helm-charts
    condition: metaMonitoring.grafanaAgent.installOperator
