apiVersion: v2
appVersion: v0.34.4
description: Grafana's Synthetic Monitoring application. The agent provides probe functionality and executes network checks for monitoring remote targets.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
maintainers:
  - email: zanhsieh@gmail.com
    name: zanhsieh
  - email: mail@torstenwalter.de
    name: torstenwalter
  - email: scott.crooks@gmail.com
    name: sc250024
name: synthetic-monitoring-agent
sources:
  - https://github.com/grafana/synthetic-monitoring-agent
type: application
version: 1.0.0
